# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: dict_minimize

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonversion: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pythonversion }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/frameworks.txt
        pip install -r requirements/tests.txt
        pip install -r requirements/tools.txt
        pip install -e .[test]
    - name: Lint
      run: |
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest tests/ -s -v --disable-pytest-warnings --hypothesis-seed=0
